# Generated by Django 4.0.4 on 2022-04-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman', models.CharField(max_length=250)),
                ('kagawad1', models.CharField(max_length=250)),
                ('kagawad2', models.CharField(max_length=250)),
                ('kagawad3', models.CharField(max_length=250)),
                ('kagawad4', models.CharField(max_length=250)),
                ('kagawad5', models.CharField(max_length=250)),
                ('kagawad6', models.CharField(max_length=250)),
                ('kagawad7', models.CharField(max_length=250)),
                ('treasurer', models.CharField(max_length=250)),
                ('secretary', models.CharField(max_length=250)),
            ],
        ),
    ]
