# Generated by Django 4.0.4 on 2022-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='chairman',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='kagawad1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='kagawad2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='kagawad3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='kagawad4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='kagawad5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='kagawad6',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='kagawad7',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='secretary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='treasurer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
