# Generated by Django 4.0.4 on 2022-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_member', '0002_alter_member_chairman_alter_member_kagawad1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='chairman',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
